### ISSUE TITLE
Featured Image support needed.

### ISSUE THREAD

**Issue by themeix** [jamwise/ghostHunter#77]
Hello,

I think you should add featured image in that search library. That would be really great.

Thanks

**Comment by jl-iges** [comment]
Hi!

Is there any workaround to show the featured images of the posts in the search results? I'm looking for a way to parse the image manually, but I don't know how.

Thanks!

**Comment by ekerstein** [comment]
Here's what I did, not sure if it's the most efficient way. But since the content API key is exposed you can just use that:

```
// post url
var url = "/ghost/api/v2/content/posts/" + result.ref + "/?key=" + ghosthunter_key;

$.get(url).done(function (data) {
     // feature image
     console.log(data.posts[0].feature_image)
});

```
